version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: platform-db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: assessment_platform
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d assessment_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: assessment-platform-be

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/assessment_platform
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL}
      BREVO_SENDER_NAME: ${BREVO_SENDER_NAME}

      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      APP_BASE_URL: ${APP_BASE_URL}

    ports:
      - "8083:8080"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: