spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assessment_platform
    username: postgres
    password: uwera@2003
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: local

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html