spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assessment_platform
    username: postgres
    password: Ariane@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true