spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

server:
  port: ${PORT:8080}

app:
  base-url: https://codeassess.com/exam

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

ADMIN_EMAIL: ${ADMIN_EMAIL}
ADMIN_PASSWORD: ${ADMIN_PASSWORD}

brevo:
  api-key: ${BREVO_API_KEY}
  sender:
    email: ${BREVO_SENDER_EMAIL}
    name: ${BREVO_SENDER_NAME}
